baseurl = "https://sharlagelfand.netlify.com/"
title = "Sharla Gelfand"
copyright = "Copyright &copy; 2019 - Sharla Gelfand"
canonifyurls = true
theme = "hugo-kiera"

paginate = 3

summaryLength = 50
enableEmoji = true
pygmentsCodeFences = true

disqusShortname = "sharlagelfand"

[author]
    name = "Sharla Gelfand"
    github = "sharlagelfand"
    twitter = "sharlagelfand"

[params]
    tagline = ""
    
[permalinks]
posts = "/posts/:slug/"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
